### ISSUE TITLE
Build error on Xcode 6.1.1

### ISSUE THREAD

**Issue by nalleyda** [simpliflow/SFBluetoothLowEnergyDevice#2]
Hi 
Im trying to build this project.

I just downloaded, pod install and try to build
but it had some error..

1) ld: library not found for -lPods-SFBluetoothLowEnergyDevice
clang: error: linker command failed with exit code 1 (use -v to see invocation)

2) error: unable to open executable '/Users/nalleyda/Library/Developer/Xcode/DerivedData/SFBLEDeviceExample-bcdmqvpmmobtanbvhjjpepuonehe/Build/Products/Debug-iphonesimulator/SFBLEDeviceExample.app/SFBLEDeviceExample'

3) CocoaLumberajack/CocoaLuberjack.h file not found

so shouldn't i use Cocoaluberjack least version?

Best
nalleyda

**Comment by TKAB** [comment]
You tried to build the example app? It seems to me you opened the project file instead of the workspace for the project?

Currently the lib depends on CocoaLumberjack 1.x. Support for 2.0 is on its way.
